import { Inter, DM_Sans } from 'next/font/google'
import './globals.css'

const dmSans = DM_Sans({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' suppressHydrationWarning>
			<head>
				<script src='https://aframe.io/releases/1.5.0/aframe.min.js'></script>
			</head>
			<body className={dmSans.className}>{children}</body>
		</html>
	)
}
